--создать таблицу с фильмами и заполнить ее значениями
DROP TABLE FILMS;
CREATE TABLE FILMS
( NAME VARCHAR2(128),
  STARS NUMBER);
  
INSERT INTO FILMS(NAME, STARS) 
VALUES('KRASOTKA V UDARE', 2);
INSERT INTO FILMS(NAME, STARS)      
VALUES('WONDER WOMAN', 3);
INSERT INTO FILMS(NAME, STARS) 
VALUES('THE QUEENS GAMBIT', 7);

--создать функцию, выдающую мои фамилию, имя и номер группы
CREATE OR REPLACE FUNCTION ABOUT_ME
RETURN VARCHAR2
IS
BEGIN
    RETURN 'POLINA LUNINA, 571';
END ABOUT_ME;
/

--выдать привилегию на просмотр таблицы и вызов функции всем пользователям oracle
GRANT SELECT ON FILMS TO PUBLIC;
GRANT EXECUTE ON ABOUT_ME TO PUBLIC;

--запрос, объединяющий все фильмы из доступных схем одногруппников и информацию о каждом владельце
SELECT NAME, STARS, IVANTYULYANDINSPACE.ABOUT_ME() AS ABOUT_OWNER 
FROM IVANTYULYANDINSPACE.FILMS
UNION
SELECT NAME, STARS, VALENTINPETROVWORKSPACE.ABOUT_ME() AS ABOUT_OWNER 
FROM VALENTINPETROVWORKSPACE.FILMS
UNION
SELECT NAME, STARS, POLINALUNINA.ABOUT_ME() AS ABOUT_OWNER 
FROM POLINALUNINA.FILMS