LOAD DATA
CHARACTERSET UTF8
INFILE 'faculties.csv'
BADFILE 'faculty.bad'
DISCARDFILE 'faculty.dsc'
APPEND
INTO TABLE FACULTY
FIELDS TERMINATED BY ';'
TRAILING NULLCOLS
	(FACULTY_LETTER CHAR,
 	FACULTY_NAME_RU)