DROP TABLE SPLIT;
DROP TABLE SAMPLE;
CREATE TABLE SAMPLE
(ID NUMBER(4,0),
 META VARCHAR(200),
 DB VARCHAR(200),
 PSEUDOKNOTS NUMBER(2,0),
 CONSTRAINT SAMPLE_PK PRIMARY KEY (ID));

INSERT INTO SAMPLE(ID, META, DB, PSEUDOKNOTS)
VALUES(1, 'cucumber green mottle mosaic virus', 'Pseudobase', 1);
INSERT INTO SAMPLE(ID, META, DB, PSEUDOKNOTS)
VALUES(2, 'Homo sapiens', 'Pseudobase', 2);
INSERT INTO SAMPLE(ID, META, DB, PSEUDOKNOTS)
VALUES(3, 'bovine coronavirus', 'Pseudobase', 1);
INSERT INTO SAMPLE(ID, META, DB, PSEUDOKNOTS)
VALUES(4, 'sugarcane yellow leaf virus', 'Pseudobase', 2);
INSERT INTO SAMPLE(ID, META, DB, PSEUDOKNOTS)
VALUES(5, 'clitoria yellow vein virus', 'Pseudobase', 1);
INSERT INTO SAMPLE(ID, META, DB)
VALUES(6, 'Hammerhead ribozyme', 'Rfam');
INSERT INTO SAMPLE(ID, META, DB)
VALUES(7, 'thermolithotrophicus.2', 'Gutell Lab CRW');
INSERT INTO SAMPLE(ID, META, DB, PSEUDOKNOTS)
VALUES(8, 'iguana', 'Gutell Lab CRW', 1);
INSERT INTO SAMPLE(ID, META, DB)
VALUES(9, 'borreli', 'Gutell Lab CRW');
INSERT INTO SAMPLE(ID, META, DB)
VALUES(10, 'Hepatitis delta virus ribozyme', 'Rfam');
INSERT INTO SAMPLE(ID, META, DB)
VALUES(11, 'Gammaretrovirus core encapsidation signal', 'Rfam');
INSERT INTO SAMPLE(ID, META, DB)
VALUES(12, 'mykiss', 'Gutell Lab CRW');
INSERT INTO SAMPLE(ID, META, DB, PSEUDOKNOTS)
VALUES(13, 'IB.PAR.', 'SRP', 3);
INSERT INTO SAMPLE(ID, META, DB)
VALUES(14, 'mauritiana', 'Gutell Lab CRW');
INSERT INTO SAMPLE(ID, META, DB)
VALUES(15, 'imentin 3 prime UTR protein-binding region', 'Rfam');

CREATE TABLE SPLIT
(ID NUMBER(4,0),
 DATASET VARCHAR(20),
 CONSTRAINT SPLIT_FK FOREIGN KEY(ID) REFERENCES SAMPLE(ID));

INSERT INTO SPLIT(ID, DATASET)
VALUES(1, 'train');
INSERT INTO SPLIT(ID, DATASET)
VALUES(2, 'test');
INSERT INTO SPLIT(ID, DATASET)
VALUES(3, 'train');
INSERT INTO SPLIT(ID, DATASET)
VALUES(4, 'valid');
INSERT INTO SPLIT(ID, DATASET)
VALUES(5, 'train');
INSERT INTO SPLIT(ID, DATASET)
VALUES(6, 'train');
INSERT INTO SPLIT(ID, DATASET)
VALUES(7, 'train');
INSERT INTO SPLIT(ID, DATASET)
VALUES(8, 'valid');
INSERT INTO SPLIT(ID, DATASET)
VALUES(9, 'test');
INSERT INTO SPLIT(ID, DATASET)
VALUES(10, 'test');
INSERT INTO SPLIT(ID, DATASET)
VALUES(11, 'train');
INSERT INTO SPLIT(ID, DATASET)
VALUES(12, 'train');
INSERT INTO SPLIT(ID, DATASET)
VALUES(13, 'valid');
INSERT INTO SPLIT(ID, DATASET)
VALUES(14, 'test');
INSERT INTO SPLIT(ID, DATASET)
VALUES(15, 'train');

SELECT JSON_OBJECT
('ID' VALUE ID,
 'meta' VALUE META,
 'database' VALUE DB,
 'hasPseudoknots' VALUE (CASE WHEN PSEUDOKNOTS IS NULL THEN 'no' ELSE 'yes' END),
 'dataset' VALUE (SELECT DATASET FROM SPLIT WHERE SAMPLE.ID = SPLIT.ID)
  FORMAT JSON) JS_DOC
FROM SAMPLE;
